---

#######################################
### CONTENT VIEW DEFAULTS
#######################################

# foreman_cv_allow_promote: false
# foreman_ccv_allow_promote: true
# foreman_ccv_auto_publish: true

### EPEL

# foreman_cv_allow_promote_epel: "{{ foreman_cv_allow_promote | bool }}"

# foreman_cv_allow_promote_epel_el7: "{{ foreman_cv_allow_promote_epel | bool }}"
# foreman_cv_allow_promote_epel_el8: "{{ foreman_cv_allow_promote_epel | bool }}"
# foreman_cv_allow_promote_epel_el9: "{{ foreman_cv_allow_promote_epel | bool }}"
